version: '3.8'

services:

  redis:
    image: redis:latest
    volumes:
      - redis_volume_learn_gpt:/data

  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/learn
    depends_on:
      - redis

volumes:
  redis_volume_learn_gpt:
