# Generated by Django 5.0.7 on 2024-07-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='count',
            field=models.IntegerField(default=5),
        ),
    ]
